export const CATALOG_VERSION = '1.0.0';

/** Metadata for all 25 audits. `implemented` flips when checks are registered. */
export const AUDIT_CATALOG = [
  {
    id: 'ssh-hardening',
    title: 'SSH Hardening',
    category: 'SERVER',
    checkCount: 7,
    estimatedSeconds: 12,
    requiresSudo: true,
    description: 'Root login, password auth, protocol, idle timeout, and related sshd settings.',
  },
  {
    id: 'application-security',
    title: 'Application Security',
    category: 'SERVER',
    checkCount: 5,
    estimatedSeconds: 10,
    requiresSudo: true,
    description: 'TLS certificates, runtime versions, database access patterns.',
  },
  {
    id: 'file-system',
    title: 'File System',
    category: 'SERVER',
    checkCount: 7,
    estimatedSeconds: 20,
    requiresSudo: true,
    description: 'Dangerous permissions, set-id binaries, sensitive files.',
  },
  {
    id: 'firewall-network',
    title: 'Firewall & Network',
    category: 'SERVER',
    checkCount: 6,
    estimatedSeconds: 15,
    requiresSudo: true,
    description: 'Firewall state, exposed ports, Docker bypass.',
  },
  {
    id: 'user-account',
    title: 'User & Account',
    category: 'SERVER',
    checkCount: 6,
    estimatedSeconds: 14,
    requiresSudo: true,
    description: 'Empty passwords, duplicate UIDs, sudo config, password aging.',
  },
  {
    id: 'kernel-sysctl',
    title: 'Kernel & Sysctl',
    category: 'SERVER',
    checkCount: 5,
    estimatedSeconds: 10,
    requiresSudo: false,
    description: 'IP forwarding, source routing, ASLR, core dumps.',
  },
  {
    id: 'updates-patching',
    title: 'Updates & Patching',
    category: 'SERVER',
    checkCount: 4,
    estimatedSeconds: 18,
    requiresSudo: true,
    description: 'Pending security updates, unattended-upgrades, reboot required.',
  },
  {
    id: 'db-authentication',
    title: 'Authentication',
    category: 'DATABASE',
    checkCount: 8,
    estimatedSeconds: 16,
    requiresSudo: true,
    description: 'Passwordless access, anonymous users, remote root.',
  },
  {
    id: 'db-configuration',
    title: 'Configuration & Hardening',
    category: 'DATABASE',
    checkCount: 7,
    estimatedSeconds: 14,
    requiresSudo: true,
    description: 'Service users, installer defaults, log placement, backups.',
  },
  {
    id: 'db-credential-storage',
    title: 'Credential Storage',
    category: 'DATABASE',
    checkCount: 4,
    estimatedSeconds: 12,
    requiresSudo: true,
    description: 'Config in web root, permissions, exposed .git.',
  },
  {
    id: 'db-network-exposure',
    title: 'Network Exposure',
    category: 'DATABASE',
    checkCount: 5,
    estimatedSeconds: 12,
    requiresSudo: true,
    description: 'Bind address, listening interfaces, firewall rules.',
  },
  {
    id: 'db-privileges',
    title: 'Privileges',
    category: 'DATABASE',
    checkCount: 5,
    estimatedSeconds: 12,
    requiresSudo: true,
    description: 'Over-privileged accounts, wildcard grants.',
  },
  {
    id: 'db-encryption',
    title: 'Encryption',
    category: 'DATABASE',
    checkCount: 4,
    estimatedSeconds: 10,
    requiresSudo: true,
    description: 'TLS for connections, at-rest encryption.',
  },
  {
    id: 'web-configuration',
    title: 'Configuration Hardening',
    category: 'WEB_SERVER',
    checkCount: 6,
    estimatedSeconds: 14,
    requiresSudo: true,
    description: 'File permissions, web root ownership, request limits.',
  },
  {
    id: 'web-content-exposure',
    title: 'Content Exposure',
    category: 'WEB_SERVER',
    checkCount: 6,
    estimatedSeconds: 12,
    requiresSudo: true,
    description: 'Directory listing, hidden files, backups, methods.',
  },
  {
    id: 'web-identification',
    title: 'Identification & Patching',
    category: 'WEB_SERVER',
    checkCount: 5,
    estimatedSeconds: 10,
    requiresSudo: true,
    description: 'Version disclosure, server tokens, outdated versions.',
  },
  {
    id: 'web-tls',
    title: 'TLS Configuration',
    category: 'WEB_SERVER',
    checkCount: 6,
    estimatedSeconds: 14,
    requiresSudo: true,
    description: 'Protocol versions, cipher suites, HSTS, certificate expiry.',
  },
  {
    id: 'web-access-control',
    title: 'Access Control',
    category: 'WEB_SERVER',
    checkCount: 4,
    estimatedSeconds: 10,
    requiresSudo: true,
    description: 'Admin endpoint protection, IP restrictions.',
  },
  {
    id: 'web-logging',
    title: 'Logging',
    category: 'WEB_SERVER',
    checkCount: 4,
    estimatedSeconds: 8,
    requiresSudo: true,
    description: 'Access and error logs, rotation, permissions.',
  },
  {
    id: 'docker-container-hardening',
    title: 'Container Hardening',
    category: 'DOCKER',
    checkCount: 5,
    estimatedSeconds: 12,
    requiresSudo: true,
    description: 'Privileged mode, user, capabilities, mounts.',
  },
  {
    id: 'docker-daemon-socket',
    title: 'Daemon & Socket',
    category: 'DOCKER',
    checkCount: 8,
    estimatedSeconds: 14,
    requiresSudo: true,
    description: 'Socket exposure, group access, rootless mode.',
  },
  {
    id: 'docker-image-vulns',
    title: 'Image Vulnerabilities',
    category: 'DOCKER',
    checkCount: 5,
    estimatedSeconds: 16,
    requiresSudo: true,
    description: 'Base image age, latest tags, registry trust.',
  },
  {
    id: 'docker-network',
    title: 'Network Configuration',
    category: 'DOCKER',
    checkCount: 5,
    estimatedSeconds: 12,
    requiresSudo: true,
    description: 'Default bridge, published ports, inter-container traffic.',
  },
  {
    id: 'docker-runtime-policy',
    title: 'Runtime Policy',
    category: 'DOCKER',
    checkCount: 5,
    estimatedSeconds: 10,
    requiresSudo: true,
    description: 'Restart policies, resource limits, health checks.',
  },
  {
    id: 'docker-secrets',
    title: 'Secrets Handling',
    category: 'DOCKER',
    checkCount: 4,
    estimatedSeconds: 10,
    requiresSudo: true,
    description: 'Secrets in environment variables and image layers.',
  },
];

export function listCatalog(implementedIds = new Set()) {
  return {
    version: CATALOG_VERSION,
    audits: AUDIT_CATALOG.map((a) => ({
      ...a,
      implemented: implementedIds.has(a.id),
    })),
  };
}

export function getAuditMeta(auditId) {
  return AUDIT_CATALOG.find((a) => a.id === auditId) ?? null;
}
